# Generated by Django 6.0.2 on 2026-03-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField()),
                ('p_id', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('status', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
