# Generated by Django 6.0.2 on 2026-03-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
