# Generated by Django 6.0.2 on 2026-03-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cart_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ord_date',
            field=models.DateField(null=True),
        ),
    ]
